### ISSUE TITLE
ESLint/Prettier Terror

### ISSUE THREAD

**Issue by charlie17** [chiubaca/vue-netlify-fauna-starter-kit#44]
Major problems compiling locally due to ESLint/Prettier errors, but I couldn't find the usual config files in this repo. Any guidance?

Thanks for doing this helpful tutorial

**Comment by chiubaca** [comment]
hi @charlie17, it's all in the `package.json` from [ln: 47](https://github.com/chiubaca/vue-netlify-fauna-starter-kit/blob/master/package.json#L47) .

What specfic errors are you getting?

**Comment by chiubaca** [comment]
@charlie17 I've just fixed a whole bunch of dependabot issues via #45. Try cloning this repo and trying again. Hopefully it works better for you now.

**Comment by charlie17** [comment]
@chiubaca Thanks for the quick follow up. Still causes a raft of lint/prettier issues. Not unique to your repo certainly, there is a ton of stuff online about the challenges of using Vue with those tools (see [this one](https://blog.jongallant.com/2019/02/vuejs-vetur-vscode-format-eslint-issues/) in particular, also [here](https://forum.vuejs.org/t/how-to-get-rid-of-the-prettier-warnings/54368)).

I ended up disabling by running `npm remove @vue/cli-plugin-eslint`

Prettier still formats the Vue file but now it doesn't throw up 100 errors when compiling/running locally (spacing, line breaks, you name it, stuff like that).

Maybe others deal with this, maybe not, but I just didn't want this crazy stuff to stand in the way of hacking around with your very helpful tutorial.

**Comment by chiubaca** [comment]
@charlie17 Yeah lint/prettier settings can be a real pain. It's usually a one off set-and-forget config for me. Odd I'm not able to replicate any errors on my end. However, glad you found a workaround, if you want to me take a deeper look at the issue, send through any logs you have, can go from there.
